### ISSUE TITLE
Hot-swap LoRA with updated llama.cpp

### ISSUE THREAD

**Issue by ltoniazzi** [undreamai/LLMUnity#212]
### Feature

Since the PRs linked below in llama.cpp, it is possible to how-swap lora adapters. This allows to personalise NPCs and other GenAi game features by fine-tuning adapters that then can be quickly swapped on the same base model in memory.

Since llama.cpp has is being updated in #209. It would be nice to check how easily one can integrate this feature. 

### Todo list

- [x] `bin` files for adapters are now deprecated in favour of new `gguf` files, which should be ameneded in the documentation, if appearing.
- [ ] Add in documentation link to how to convert adapters to `gguf`.
- [x] Test on using the new gguf formats should be run (I suspect the new adapter will automatically be used in hot-swapping mode)
- [x] Test using multiple adapters and hot swapping them, add code if needed, and add an example in the examples folder.

### Related links

Hot lora PRs in llama.cpp:
- Cli: https://github.com/ggerganov/llama.cpp/pull/8332
- Server: https://github.com/ggerganov/llama.cpp/pull/8857

Discord threads:
- [Discussion on lora](https://discord.com/channels/1194779009284841552/1265657308244086815/1266469723240140832)

**Comment by ltoniazzi** [comment]
I am happy to have a go at it 😃

**Comment by amakropoulos** [comment]
Wow thanks for the detailed request ⭐!
I implemented multiple loras and hot swapping in #210 . Do you want to have a look at it and let me know what you think?
I haven't added a sample or description in the Readme yet.

**Comment by amakropoulos** [comment]
I added a unit test for lora at #219 .
I'm adding some documentation and will release once I fix some build issue.
